#!/usr/bin/python3
from sys import argv
argv.pop(0)
# argv = argv[0].split(" ")

r = int(argv[0])
b = int(argv[1])
b = int(argv[2])

print(f"#{hex(r).replace('0x', '')}{hex(b).replace('0x', '')}{hex(b).replace('0x', '')}")
