#!/usr/bin/python3
from random import randint, choice

the_list = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

for i in range(65, 90):
    the_list.append(chr(i))

for i in range(97, 122):
    the_list.append(chr(i))

nofc = randint(3, 7)
proname = ""
for i in range(nofc):
    proname += str(choice(the_list))

print(proname)

